# Generated by Django 3.2.4 on 2021-06-19 14:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chatUSer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cedula')),
                ('name', models.CharField(help_text='Ingrese su nombre', max_length=100)),
                ('lastName', models.CharField(help_text='Ingrese su apellido', max_length=100)),
                ('cellPhone', models.BigIntegerField(blank=True, help_text='Ingrese su Celular', null=True)),
                ('email', models.EmailField(help_text='Ingrese su email', max_length=200)),
                ('addres', models.CharField(blank=True, help_text='Ingrese su direcció', max_length=200, null=True)),
                ('birhtDate', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, help_text='M -> Masculino, F-> Femenino, O ->Otro', max_length=1, null=True)),
                ('isAdmin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'chatUser',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10000000)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.CharField(max_length=1000000)),
                ('room', models.CharField(max_length=100000)),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('idMeet', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('assigDate', models.DateTimeField()),
                ('toDay', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('ccDoc', models.BigIntegerField()),
                ('state', models.CharField(choices=[('CI', 'Check-in'), ('CO', 'Check-out'), ('CD', 'Cancelada'), ('AT', 'asistio')], max_length=2)),
                ('ccUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'meet',
                'verbose_name_plural': 'meets',
                'db_table': 'meet',
            },
        ),
    ]
